### ISSUE TITLE
点击按钮无响应

### ISSUE THREAD

**Issue by ALCoding** [louis-ly/LYSideslipCell#1]
按钮点击事件无响应,望解决.

**Comment by louis-ly** [comment]
感谢提醒！！
其实问题早解决了，不知道为什么从github上下下来的是老版本
现在应该没问题了~！
以后还有什么问题还望指出，感谢！

**Comment by ALCoding** [comment]
问题是出在哪里呢?

**Comment by louis-ly** [comment]
为了让使用者在创建自定义cell的时候，可以直接调用`[self addSubview:view];`方法来添加视图，，而不是必须得调用`[self.contentView addSubview:view];` 我就用Method Swizzle交互了该类的addSubview方法。

```
- (void)ly_addSubview:(UIView *)view {
    if ([view isKindOfClass:NSClassFromString(@"UITableViewCellContentView")] || [view isKindOfClass:NSClassFromString(@"_UITableViewCellSeparatorView")] || [view isKindOfClass:LYSideslipView.class]) {
        [self ly_addSubview:view];
    } else {
        [self.contentView addSubview:view];
    }
}
```

因为除了类里写的视图是需要直接添加在cell上面，其他的开发者直接创建的视图都是需要加在contentView上面，才可以在滚动的时候被带着滚动的。
这个方法的就是判断，UITableViewCellContentView、_UITableViewCellSeparatorView、LYSideslipView这三种视图是添加在self上面，其他调用添加到self.contentView上面。

当时你下的版本是少了`[view isKindOfClass:LYSideslipView.class]`判断，导致_sideslipContainView这个视图添加到了contentView上，再加上约束的错乱就导致了的问题。虽然按钮能看得见，但实际点不了。

抱歉今天才注意到github的问题，回答晚了

**Comment by hanjunqiang** [comment]
分段加载数据的时候，一次加载10条，删除之后，下拉刷新加载数据，不能侧滑出删除按钮，就连点击cell也不行了。这是哪里出现问题了？

**Comment by louis-ly** [comment]
前阵子也重写过, 希望能解决掉你们的问题
