### ISSUE TITLE
cell无法回复到初始状态

### ISSUE THREAD

**Issue by Rob-wang** [louis-ly/LYSideslipCell#2]
继承LYSideslipCell，用代码重写- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier方法，左滑后，无法回复到初始状态，有10左右的偏差
![2017-02-16 3 52 55](https://cloud.githubusercontent.com/assets/6449073/23012238/3023e944-f460-11e6-88db-625fa8cf8718.png)

**Comment by Rob-wang** [comment]
调用这个方法就没问题了。。。
- (void)layoutSubviews {
    [super layoutSubviews];
    
    CGRect frame = self.contentView.frame;
    frame.size.width = self.bounds.size.width;
    self.contentView.frame = frame;
}

**Comment by louis-ly** [comment]
嗯   我回头把这段代码在类里加一份
