### ISSUE TITLE
cell被选中，备注文字也显示出来

### ISSUE THREAD

**Issue by Rob-wang** [louis-ly/LYSideslipCell#4]
1. 长按cell（头像）一段时间后，向下移动，取消选中状态后，松开手指
2. 此时去按下之前那个cell，备注文字会显示成白色

**Comment by Rob-wang** [comment]
![2017-03-22 10 07 58](https://cloud.githubusercontent.com/assets/6449073/24179184/877acf9e-0ee8-11e7-9e11-c16edee6969a.png)

**Comment by louis-ly** [comment]
抱歉回复晚了
这个问题好像两个月前就应该解决了。你拉拉最新代码看看
